export const CANDIDATE = {
  name: 'Richard Kuhne',
  location: 'Los Angeles, California',
  positioning: 'PRODUCTION OPERATIONS · AI SYSTEMS · WORKFLOW AUTOMATION',

  summary:
    'Experienced production executive, line producer and production manager with extensive unscripted television, digital and branded-content experience, now combining that production-operating background with hands-on AI systems design, agentic workflows, workflow automation and independent digital-product development.',

  productionExperience: [
    'production operations',
    'line producing',
    'production management',
    'budgeting',
    'cost tracking',
    'scheduling',
    'crew management',
    'vendor management',
    'production logistics',
    'locations',
    'travel',
    'permits',
    'insurance',
    'payroll preparation',
    'contracts',
    'cross-department coordination',
    'simultaneous productions',
    'production problem solving',
    'vendor negotiation',
    'delivery coordination',
    'legal/accounting/HR coordination',
  ],

  aiSystemsExperience: [
    'agentic workflow design',
    'AI-assisted development',
    'structured skills and SOPs',
    'API integrations',
    'MCP integrations',
    'human-in-the-loop systems',
    'AI workflow architecture',
    'multi-model workflows',
    'AI-assisted research',
    'operational decision support',
    'source-backed reasoning',
    'information normalization',
    'exception detection',
  ],

  mediaProductExperience: [
    'unscripted television',
    'digital content',
    'branded content',
    'AI-assisted production',
    'research systems',
    'digital publishing',
    'audience development',
    'emerging media',
  ],

  proofProjects: {
    FIELDPLAN: {
      description:
        'A live agentic production-operations prototype designed around real-world film and television workflows.',
      features: [
        'schedules',
        'crew',
        'documents',
        'SOPs',
        'exceptions',
        'approval workflows',
        'source-backed exception detection',
        'document-authority logic',
        'conflict identification',
        'human-in-the-loop decision gates',
        'modular production rules',
      ],
    },
    'PDUFA PULSE': {
      description:
        'AI-assisted biotech intelligence publication using multimodel research, verification, probability assessment, catalyst tracking and repeatable publishing workflows.',
    },
    'THE PICKUP': {
      description:
        'Entertainment intelligence product using structured research, information architecture and AI-assisted publishing.',
    },
  },

  previousExperience: {
    NBCUniversalDigitalLab: {
      roles: ['Line Producer', 'Staff Production Manager'],
      work: [
        'unscripted series',
        'digital programming',
        'branded content',
        'simultaneous productions',
        'crews',
        'staff',
        'schedules',
        'hiring',
        'crew booking',
        'locations',
        'sets',
        'equipment',
        'travel',
        'permits',
        'insurance',
        'budgets',
        'tracking',
        'cost reports',
        'contracts',
        'accounting',
        'HR coordination',
        'vendor management',
        'negotiation',
        'production logistics',
        'delivery',
      ],
    },
    freelance: 'Additional freelance line-producing and production-management work across networks including HGTV, TLC, PBS and Discovery.',
  },

  targetRoleFamilies: [
    {
      name: 'AI + PRODUCTION / MEDIA OPERATIONS',
      examples: [
        'Director, AI Production',
        'AI Production Lead',
        'Production Innovation',
        'Production Technology',
        'AI Workflow Lead',
        'Creative Technology Operations',
        'Media AI Operations',
        'Production Systems',
        'Workflow Automation',
        'Production Transformation',
      ],
    },
    {
      name: 'PRODUCTION / CONTENT OPERATIONS',
      examples: [
        'Director of Production',
        'Head of Production Operations',
        'Production Executive',
        'Senior Production Manager',
        'Creative Operations Director',
        'Content Operations Director',
        'Studio Operations',
        'Production Strategy',
        'Media Operations',
      ],
    },
    {
      name: 'MEDIA / CREATIVE TECHNOLOGY',
      examples: [
        'Creative Technology',
        'Creative Systems',
        'AI Enablement for Creative Teams',
        'Content Technology',
        'Media Technology Operations',
        'AI Adoption',
        'Workflow Transformation',
      ],
    },
    {
      name: 'PRODUCT / PROGRAM / OPERATIONS',
      examples: [
        'Product Operations',
        'Program Operations',
        'Media Product Operations',
        'AI Program Manager',
        'AI Operations',
        'Workflow Program Manager',
      ],
    },
  ],

  negativeFitSignals: [
    'professional software engineering',
    'ML engineering',
    'ML research',
    'quantitative research',
    'DevOps / SRE',
    'quota-carrying enterprise sales',
    'specialized accounting',
    'specialized HR/recruiting',
    'licensed professions',
    'entry-level experience',
  ],

  neverDescribeAs: [
    'software engineer',
    'machine-learning engineer',
    'data scientist',
    'computer scientist',
    'full-stack engineer',
    'enterprise salesperson',
    'quota-carrying salesperson',
    'attorney',
    'CPA',
    'HR specialist',
  ],
} as const;
